In [11]:
import numpy as np
import pandas as pd

In [12]:
movie = pd.read_csv('imdb-top-1000.csv')
movie.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

In [14]:
genre = movie.groupby('Genre')

In [20]:
genre.sum().head(1)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0

 find the top 3 genres by total earning

In [27]:
movie.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

 find the genre with highest avg IMDB rating

In [33]:
movie.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

find director with most popularity

In [40]:
movie.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

find the highest rated movie of each genre

In [ ]:
movie.groupby('Genre')['IMDB_Rating'].max()

        Genre  IMDB_Rating
0      Action          9.0
1   Adventure          8.6
2   Animation          8.6
3   Biography          8.9
4      Comedy          8.6
5       Crime          9.2
6       Drama          9.3
7      Family          7.8
8     Fantasy          8.1
9   Film-Noir          8.1
10     Horror          8.5
11    Mystery          8.4
12   Thriller          7.8
13    Western          8.8

find number of movies done by each actor

In [46]:
movie.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)

Star1
Tom Hanks             12
Robert De Niro        11
Clint Eastwood        10
Al Pacino             10
Leonardo DiCaprio      9
                      ..
Glen Hansard           1
Giuseppe Battiston     1
Giulietta Masina       1
Gerardo Taracena       1
Ömer Faruk Sorak       1
Name: Series_Title, Length: 660, dtype: int64